GET http://localhost:3000/golden-raspberry-awards


###
GET http://localhost:3000/golden-raspberry-awards/826ecb9f-5988-4b34-be41-8a677d3950c0

### get-producer
GET  http://localhost:3000/golden-raspberry-awards/get-producer-longer-interval-between-awards


###
POST http://localhost:3000/golden-raspberry-awards
Content-Type: application/json

{
  "year": 1999,
  "title": "Homem de ferro",
  "studios": "Marvel",
  "producers": "",
  "winner": true
}

###
PATCH http://localhost:3000/golden-raspberry-awards/826ecb9f-5988-4b34-be41-8a677d3950c0
Content-Type: application/json

{
  "year": 2000,
  "title": "Homem de ferro",
  "studios": "Marvel",
  "producers": "Carlos Olveira",
  "winner": true
}
